### ISSUE TITLE
What's the different between version 2 and current ?

### ISSUE THREAD

**Issue by fnaith** [MahjongRepository/mahjong#48]
I think the logic of this library is very clear, and curious about this sentence in wiki:

`Version 2.x is under heavy development. If you want to contribute, please reach out the maintainers.`

**Comment by Nihisil** [comment]
@fnaith hi there! I was thinking of updating the library with more strict typing and using Pydantic models for data exchange between modules rather than dictionaries. I also planned to fine-tune the library's code to improve performance, but I'm currently swamped and can't work on it. So, there's no progress with version 2 at the moment. I've gone ahead and deleted that sentence from the wiki. Thanks!

**Comment by fnaith** [comment]
Looking forward for typing and new algorithm !
